apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_URI: "mongodb://admin:password@mongo-0.mongo:27017/mydb?authSource=admin"